default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: bartosz
  password: 123

development:
  <<: *default
  database: my_api_development
test:
  <<: *default
  database: my_api_test
production:
  <<: *default
  database: my_api_production
  username: my_api
  password: <%= ENV['MY_API_DATABASE_PASSWORD'] %>
