# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21289e0bcc8ddc426ac8e61e5c7a57310ac69299dd326ae791f54a499505041314648797e58713f4b80ad58785d94de23e0881c36b334042705f33a43ad1a559

test:
  secret_key_base: 3a73a00465bfe6fe7b10b31e905fdf2b5a692eec9b6fac4b258360f8e234b4f6817ac0404329938f0eac1f8ac2fff31fc4c98adf77dc7c462a053172f71c28e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
